#
# http://wiki.ros.org/move_base

# This needs to be non-zero, otherwise the global planner never replans around new obstacles
planner_frequency:          0.5     # default: 0.0 Global plan updates on new goal or path blocked only

controller_frequency:       10.0    # default: 20.0
planner_patience:           5.0     # default: 5.0
controller_patience:        10.0    # default: 15.0
conservative_reset_dist:    3.0     # default: 3.0
recovery_behavior_enabled:  true    # default: true
clearing_rotation_allowed:  true    # default: true
shutdown_costmaps:          false   # default: false
oscillation_timeout:        5.0     # default: 0.0
oscillation_distance:       0.05     # default: 0.5

# Order matters here. The robot will execute each one and then try replanning,
# and if planning fails it will go one to the next. If it still can't plan after
# trying all of them then it will abort
recovery_behaviors: [
  {name: straf_recovery, type: straf_recovery/StrafRecovery},
  {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
  {name: rotate_recovery1, type: rotate_recovery/RotateRecovery},
  {name: aggressive_straf_recovery, type: straf_recovery/StrafRecovery},
  {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
  {name: rotate_recovery2, type: rotate_recovery/RotateRecovery}

]

conservative_clear:
  reset_distance: 3.0

# as confusing as it seems, 0 actually means *everything*
# so this will clear the entire map, and it will then be re-initialized
# from the static map
aggressive_clear:
  reset_distance: 0.0


straf_recovery:
  timeout: 5 #default 10
  straf_vel: 0.1 #default: 0.1

aggressive_straf_recovery:
  timeout: 15 #default 10
  straf_vel: 0.1 #default: 0.1
